In [2]:
import yfinance as yf

In [3]:
# List of WIG20 stock
wig20_stock = [
    'ALR.WA', 'ALE.WA', 'BDX.WA', 'CDR.WA', 'CPS.WA',
    'DNP.WA', 'JSW.WA', 'KGH.WA', 'KTY.WA', 'KRU.WA',
    'LPP.WA', 'MBK.WA', 'OPL.WA', 'PEO.WA', 'PCO.WA', 
    'PGE.WA', 'PKN.WA', 'PKO.WA', 'PZU.WA', 'SPL.WA'
]

In [4]:
# Download data
w20_stock = yf.download(wig20_stock, period="max", interval="1d")

# Rename columns
w20_stock.columns = ['_'.join(col).strip() for col in w20_stock.columns.values]
w20_stock

[*********************100%%**********************]  20 of 20 completed

,Adj Close_ALE.WA,Adj Close_ALR.WA,Adj Close_BDX.WA,Adj Close_CDR.WA,Adj Close_CPS.WA,Adj Close_DNP.WA,Adj Close_JSW.WA,Adj Close_KGH.WA,Adj Close_KRU.WA,Adj Close_KTY.WA,...,Volume_LPP.WA,Volume_MBK.WA,Volume_OPL.WA,Volume_PCO.WA,Volume_PEO.WA,Volume_PGE.WA,Volume_PKN.WA,Volume_PKO.WA,Volume_PZU.WA,Volume_SPL.WA
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-03,NaN,NaN,9.774726,36.106373,NaN,NaN,NaN,8.095845,NaN,20.975525,...,NaN,26542,464728,NaN,32578,NaN,365290,NaN,NaN,NaN
2000-01-04,NaN,NaN,9.270225,35.329933,NaN,NaN,NaN,7.701665,NaN,19.894312,...,NaN,36881,272795,NaN,152183,NaN,510454,NaN,NaN,NaN
2000-01-05,NaN,NaN,9.112568,35.135777,NaN,NaN,NaN,7.671342,NaN,19.533903,...,NaN,26211,244291,NaN,126395,NaN,732032,NaN,NaN,NaN
2000-01-06,NaN,NaN,9.144098,35.291080,NaN,NaN,NaN,7.580380,NaN,19.461826,...,NaN,13591,100300,NaN,44067,NaN,388866,NaN,NaN,NaN
2000-01-07,NaN,NaN,9.711663,40.376987,NaN,NaN,NaN,8.459704,NaN,20.831362,...,NaN,32972,589542,NaN,65572,NaN,454879,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-07-15,36.674999,101.150002,684.500000,163.800003,12.170,407.500000,28.150000,153.350006,469.600006,855.000000,...,2087.0,16567,1038461,1046090.0,380715,1147757.0,990387,1671889.0,605503.0,62283.0
2024-07-16,35.880001,96.400002,672.500000,160.500000,11.370,395.100006,27.780001,145.750000,456.000000,843.000000,...,4613.0,26077,1002562,1698971.0,571453,1941951.0,2425555,2840944.0,1750638.0,63522.0
2024-07-17,34.779999,94.099998,657.500000,159.800003,11.440,396.899994,27.700001,145.300003,454.799988,833.500000,...,5304.0,25591,1114432,2694810.0,709034,2838611.0,2447891,2073575.0,1849457.0,64615.0
2024-07-18,35.299999,97.180000,664.000000,161.800003,11.760,407.299988,29.180000,142.250000,458.200012,832.500000,...,3861.0,23085,3087063,1132700.0,525320,1380202.0,1705800,3315933.0,2360863.0,61932.0
2024-07-19,35.130001,97.040001,659.000000,157.500000,11.515,402.799988,28.809999,137.399994,454.200012,855.000000,...,2203.0,13547,715370,608415.0,747089,979019.0,803435,2684152.0,988262.0,41468.0

In [5]:
w20_stock.to_csv('./data_files/w20_stock.csv')