In [1]:
import pandas as pd

In [2]:
# Reading data, renaming columns and reordering
w20_stock_close = pd.read_csv('./data_files/w20_stock.csv').filter(regex='^Close_')
w20_stock_close.columns = [x.split('_')[1].split('.')[0] for x in w20_stock_close.columns]
w20_stock_close['Date'] = pd.read_csv('./data_files/w20_stock.csv')['Date']
w20_stock_close.insert(0, 'Date', w20_stock_close.pop('Date'))

# Close_PCO.WA limits data range
w20_stock_close = w20_stock_close.loc[w20_stock_close['Date'] > '2021-05-26'].reset_index(drop=True)
w20_stock_close.head()

,Date,ALE,ALR,BDX,CDR,CPS,DNP,JSW,KGH,KRU,...,LPP,MBK,OPL,PCO,PEO,PGE,PKN,PKO,PZU,SPL
0,2021-05-27,58.279999,32.900002,313.5,175.500000,30.700001,283.899994,36.299999,200.000000,247.600006,...,11040.0,297.799988,6.695,44.000000,93.760002,10.025,78.279999,39.290001,36.169998,265.700012
1,2021-05-28,58.500000,33.990002,306.0,178.580002,30.700001,285.000000,36.310001,202.899994,258.000000,...,11470.0,300.000000,6.710,44.645000,95.500000,10.165,79.940002,39.799999,36.900002,271.299988
2,2021-05-31,57.660000,33.740002,298.5,168.740005,30.500000,284.600006,36.490002,202.000000,258.000000,...,11200.0,302.399994,6.650,44.000000,95.959999,9.986,81.800003,40.669998,37.060001,267.000000
3,2021-06-01,59.209999,34.480000,299.0,153.380005,30.760000,283.799988,34.799999,208.800003,262.000000,...,11320.0,307.000000,6.680,44.000000,96.699997,9.936,81.680000,39.950001,37.290001,269.000000
4,2021-06-02,59.180000,34.410000,295.0,161.580002,31.620001,286.100006,34.849998,209.500000,278.600006,...,11360.0,300.000000,6.700,43.735001,97.260002,10.240,81.180000,40.090000,37.900002,271.299988

In [3]:
for stock in w20_stock_close.columns.drop('Date'):
    w20_stock_close[stock] = (w20_stock_close[stock] - w20_stock_close[stock].shift(1)) / w20_stock_close[stock].shift(1)
w20_stock_close

,Date,ALE,ALR,BDX,CDR,CPS,DNP,JSW,KGH,KRU,...,LPP,MBK,OPL,PCO,PEO,PGE,PKN,PKO,PZU,SPL
0,2021-05-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-05-28,0.003775,0.033131,-0.023923,0.017550,0.000000,0.003875,0.000276,0.014500,0.042003,...,0.038949,0.007388,0.002240,0.014659,0.018558,0.013965,0.021206,0.012980,0.020183,0.021076
2,2021-05-31,-0.014359,-0.007355,-0.024510,-0.055101,-0.006515,-0.001403,0.004957,-0.004436,0.000000,...,-0.023540,0.008000,-0.008942,-0.014447,0.004817,-0.017609,0.023267,0.021859,0.004336,-0.015850
3,2021-06-01,0.026882,0.021932,0.001675,-0.091028,0.008525,-0.002811,-0.046314,0.033663,0.015504,...,0.010714,0.015212,0.004511,0.000000,0.007712,-0.005007,-0.001467,-0.017703,0.006206,0.007491
4,2021-06-02,-0.000507,-0.002030,-0.013378,0.053462,0.027958,0.008104,0.001437,0.003352,0.063359,...,0.003534,-0.022801,0.002994,-0.006023,0.005791,0.030596,-0.006121,0.003504,0.016358,0.008550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,2024-07-15,-0.003397,0.000000,0.000000,0.033113,0.001646,0.008663,0.005357,-0.016987,-0.004241,...,-0.006865,0.010261,-0.012955,-0.024866,0.009988,-0.007355,-0.001485,-0.001632,0.012714,0.011020
788,2024-07-16,-0.021677,-0.046960,-0.017531,-0.020147,-0.065735,-0.030429,-0.013144,-0.049560,-0.028961,...,-0.038018,-0.039397,-0.018425,-0.012500,-0.038394,-0.036773,-0.033026,-0.024518,-0.042762,-0.036568
789,2024-07-17,-0.030658,-0.023859,-0.022305,-0.004361,0.006157,0.004556,-0.002880,-0.003087,-0.002632,...,-0.017964,-0.013137,-0.008228,-0.036709,-0.019964,0.000570,-0.005538,-0.013405,-0.012090,-0.018613
790,2024-07-18,0.014951,0.032731,0.009886,0.012516,0.027972,0.026203,0.053430,-0.020991,0.007476,...,0.018293,0.030519,0.015297,0.032852,0.013889,0.014522,0.008199,0.036005,0.020535,0.015991
791,2024-07-19,-0.004816,-0.001441,-0.007530,-0.026576,-0.020833,-0.011048,-0.012680,-0.034095,-0.008730,...,-0.018563,0.009767,-0.003320,-0.015267,-0.003957,0.004210,0.000153,-0.013770,-0.005691,0.003294